### ISSUE TITLE
Remove dependency to Blob Storage in Webhost

### ISSUE THREAD

**Issue by branimirangelov** [obecto/perper#25]
[14:46:36 WRN] Breaking change analysis operation failed
System.InvalidOperationException: The BlobChangeAnalysisStateProvider requires the default storage account 'Storage', which is not defined.
   at Microsoft.Azure.WebJobs.Script.ChangeAnalysis.BlobChangeAnalysisStateProvider.GetCurrentAsync(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.WebHost/BreakingChangeAnalysis/BlobChangeAnalysisStateProvider.cs:line 40
   at Microsoft.Azure.WebJobs.Script.ChangeAnalysis.ChangeAnalysisService.TryLogBreakingChangeReportAsync(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.WebHost/BreakingChangeAnalysis/ChangeAnalysisService.cs:line 92

**Comment by branimirangelov** [comment]
Consider as part of #40

**Comment by branimirangelov** [comment]
In relation with #41 we have to increase Azure Function Runtime version to:

Azure Functions Core Tools (3.0.2931 Commit hash: d552c6741a37422684f0efab41d541ebad2b2bd2)
Function Runtime Version: 3.0.14492.0

The issue is no longer present in this Azure Functions Runtime version
