### ISSUE TITLE
Perper functions cannot contain underscore in their FunctionName

### ISSUE THREAD

**Issue by bojidar-bg** [obecto/perper#5]
For example:
```cs
namespace DotNet.FunctionApp
{
    public static class SampleService
    {
        [FunctionName("sample_service")]
        public static async Task Run([PerperStreamTrigger] PerperStreamContext context,
            CancellationToken cancellationToken)
        {
            await context.BindOutput(cancellationToken);
        }

        [FunctionName("Launcher")]
        public static async Task Run([PerperStreamTrigger(RunOnStartup = true)] PerperStreamContext context,
            CancellationToken cancellationToken)
        {
            await using var sample = await context.StreamActionAsync("sample_service", new {});
            await context.BindOutput(cancellationToken);
        }
    }
}
```
Results in:
```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (99): Cannot assign requested address /tmp/perper/sample.sock
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at Perper.Fabric.Transport.FunctionConnection..ctor(String delegateName) in obecto/perper/src/Perper.Fabric/Transport/FunctionConnection.cs:line 18
   at Perper.Fabric.Services.StreamService.Init(IServiceContext context) in obecto/perper/src/Perper.Fabric/Services/StreamService.cs:line 38
Mar 03, 2020 5:34:39 PM org.apache.ignite.logger.java.JavaLogger error
SEVERE: Failed to initialize service (service will not be deployed): e06240ac-654a-4de5-9e2f-004c997da7b0
class org.apache.ignite.IgniteException: Native platform exception occurred.
        at org.apache.ignite.internal.util.IgniteUtils.convertException(IgniteUtils.java:1029)
        at org.apache.ignite.internal.processors.platform.services.PlatformAbstractService.init(PlatformAbstractService.java:107)
        at org.apache.ignite.internal.processors.service.GridServiceProcessor.redeploy(GridServiceProcessor.java:1364)
        at org.apache.ignite.internal.processors.service.GridServiceProcessor.processAssignment(GridServiceProcessor.java:1988)
        at org.apache.ignite.internal.processors.service.GridServiceProcessor.onSystemCacheUpdated(GridServiceProcessor.java:1615)
        at org.apache.ignite.internal.processors.service.GridServiceProcessor.access$300(GridServiceProcessor.java:126)
        at org.apache.ignite.internal.processors.service.GridServiceProcessor$ServiceEntriesListener$1.run0(GridServiceProcessor.java:1597)
        at org.apache.ignite.internal.processors.service.GridServiceProcessor$DepRunnable.run(GridServiceProcessor.java:2064)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by branimirangelov** [comment]
Planned for 0.3
