### ISSUE TITLE
For verification: Large objects lead to stall in streams

### ISSUE THREAD

**Issue by branimirangelov** [obecto/perper#62]
Send large object before the previous is handled by the listening stream leads to stalling.

**Comment by branimirangelov** [comment]
@vikvelev

**Comment by bojidar-bg** [comment]
Debugged the issue using the submitted code, it was reproducible under both 0.4.x and 0.5.1.
It turned out to be a problem while deserializing an element of a [`Newtonsoft.Json.Linq.JArray`](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Linq_JArray.htm), likely a [`Newtonsoft.Json.Linq.JObject`](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Linq_JObject.htm). From there, it seems like Ignite tried to deserialize [`JPropertyKeyedCollection.Comparer`](https://github.com/JamesNK/Newtonsoft.Json/blob/cdf10151d507d497a3f9a71d36d544b199f73435/Src/Newtonsoft.Json/Linq/JPropertyKeyedCollection.cs#L37), a `private readonly static` property.

<details> <summary>Sample stack trace:</summary>

```
System.Runtime.Serialization.SerializationException: The constructor to deserialize an object of type 'System.OrdinalCaseSensitiveComparer' was not found.                                                                                                                                                    
   at Apache.Ignite.Core.Impl.Common.SerializableTypeDescriptor.get_SerializationCtorUninitialized()
   at Apache.Ignite.Core.Impl.Binary.SerializableSerializer.ReadBinary[T](BinaryReader reader, IBinaryTypeDescriptor desc, Int32 
   at Apache.Ignite.Core.Impl.Binary.BinaryReader.ReadFullObject[T](Int32 pos, Type typeOverride)
   at Apache.Ignite.Core.Impl.Binary.BinaryReader.TryDeserialize[T](T& res, Type typeOverride)
   at Apache.Ignite.Core.Impl.Binary.BinaryReader.Deserialize[T](Type typeOverride)
   at Apache.Ignite.Core.Impl.Binary.BinaryReader.ReadObject[T](String fieldName)
   at Apache.Ignite.Core.Impl.Binary.SerializableSerializer.ReadSerializationInfo(BinaryReader reader, IEnumerable`1 fieldNames, Type type, ICollection`1 dotNetFields)                                                                                                                                                                                         
   at Apache.Ignite.Core.Impl.Binary.SerializableSerializer.ReadBinary[T](BinaryReader reader, IBinaryTypeDescriptor desc, Int32 pos, Type typeOverride)
[.. recursive ..]
   at Apache.Ignite.Core.Impl.Binary.BinaryReader.ReadFullObject[T](Int32 pos, Type typeOverride)
   at Apache.Ignite.Core.Impl.Binary.BinaryReader.TryDeserialize[T](T& res, Type typeOverride)
   at Apache.Ignite.Core.Impl.Binary.BinaryReader.Deserialize[T](Type typeOverride)
   at Apache.Ignite.Core.Impl.Binary.BinaryReader.ReadObject[T](String fieldName)
   at lambda_method(Closure , Object , IBinaryReader )
   at Apache.Ignite.Core.Impl.Binary.BinaryReflectiveSerializerInternal.Apache.Ignite.Core.Impl.Binary.IBinarySerializerInternal.ReadBinary[T](BinaryReader reader, IBinaryTypeDescriptor desc, Int32 pos, Type typeOverride)
[.. /recursive ..]
   at Apache.Ignite.Core.Impl.Binary.BinaryReader.ReadFullObject[T](Int32 pos, Type typeOverride)
   at Apache.Ignite.Core.Impl.Binary.BinaryReader.TryDeserialize[T](T& res, Type typeOverride)
   at Apache.Ignite.Core.Impl.Binary.BinaryReader.Deserialize[T](Type typeOverride)
   at Apache.Ignite.Core.Impl.Binary.BinaryReader.ReadBinaryObject[T](Boolean doDetach)
   at Apache.Ignite.Core.Impl.Binary.BinaryReader.TryDeserialize[T](T& res, Type typeOverride)
   at Apache.Ignite.Core.Impl.Binary.BinaryReader.Deserialize[T](Type typeOverride)
   at Apache.Ignite.Core.Impl.Binary.Marshaller.Unmarshal[T](IBinaryStream stream, BinaryMode mode, BinaryObjectBuilder builder)
   at Apache.Ignite.Core.Impl.Binary.Marshaller.Unmarshal[T](IBinaryStream stream, Boolean keepBinary)
   at Apache.Ignite.Core.Impl.Client.Cache.CacheClient`2.UnmarshalNotNull[T](ClientResponseContext ctx)
   at Apache.Ignite.Core.Impl.Client.Cache.CacheClient`2.<GetAsync>b__2(ClientResponseContext ctx)
   at Apache.Ignite.Core.Impl.Client.ClientSocket.DecodeResponse[T](BinaryHeapStream stream, Func`2 readFunc, Func`3 errorFunc)
   at Apache.Ignite.Core.Impl.Client.ClientSocket.<>c__DisplayClass1`1.<DoOutInOpAsync>b__0(Task`1 responseTask)
[.. task dispatcher ..]
   at Perper.WebJobs.Extensions.Services.PerperFabricContext.WriteNotificationToChannel(Notification notification, String streamName, String parameterName) in /home/bobo/Projects/obecto/perper/functions/runtime/src/Perper.WebJobs.Extensions/Services/PerperFabricContext.cs:line 282
   at Perper.WebJobs.Extensions.Services.PerperFabricContext.RouteNotification(Notification notification) in /home/bobo/Projects/obecto/perper/functions/runtime/src/Perper.WebJobs.Extensions/Services/PerperFabricContext.cs:line 259
   at Perper.WebJobs.Extensions.Services.PerperFabricContext.<>c__DisplayClass9_1.<<StartListen>b__3>d.MoveNext() in /home/bobo/Projects/obecto/perper/functions/runtime/src/Perper.WebJobs.Extensions/Services/PerperFabricContext.cs:line 123
```

</details>


Added some logging in 0.5.2 (e33f9ce1caaf4f24165d76710a3a388ab1084987), and made sure that a deserialization failure does not cause a complete stop of message processing, which should help debug and handle instances of similar issues in the future.

As `Newtonsoft.Json` support is not blocking for 0.6, the milestone could be removed. A valid workaround for the time being is passing the value as a JSON-encoded `String`.
